# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox

exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = sleep 1 && killall -e xdg-desktop-portal-hyprland & killall -e xdg-desktop-portal-gtk & killall xdg-desktop-portal && /usr/lib/xdg-desktop-portal-hyprland & /usr/lib/xdg-desktop-portal-gtk & /usr/lib/xdg-desktop-portal &
exec-once = dbus-monitor --session
exec-once = nwg-look -a
exec-once = /usr/bin/swaync 
exec-once = /usr/bin/swaync-client --reload-config ; /usr/bin/swaync-client --reload-css
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
exec-once = awww-daemon
exec-once = playerctld daemon
# exec-once = hypridle
# exec-once = eww daemon
exec-once = lf -server
exec-once = emacs --daemon

# WorkSpaces
exec-once = [workspace 2 silent] firefox-esr
exec-once = [workspace 1 silent] sleep 1 && obsidian
exec-once = [workspace 9 silent] /usr/bin/ferdium --enable-features=WaylandWindowDecorations --ozone-platform-hint=wayland

# Exec
exec = sleep 0.3 && awww img --transition-duration 1 --transition-step 1 --transition-type none --outputs eDP-1 Camping.png
exec = sleep 0.3 && awww img --transition-duration 1 --transition-step 1 --transition-type none --outputs HDMI-A-1 Opportunity.png
exec = sleep 0.3 && awww img --transition-duration 1 --transition-step 1 --transition-type none --outputs DP-1 relax.png

# Grayscale_legacy
exec = hyprshade on grayscale

# PowerOn Sound
exec-once = sleep 4 && find /home/deathgabox/.local/startup/ -type f | shuf -n 1 | xargs -d "\n" mpv
