# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# Example NEW WindowsRule v2
# windowsrule = match:class program, option


# General Config
# No Borders and No Rounding


# Float

windowrule = match:class floating, float on
windowrule = match:class ^(imv)$, float on
windowrule = match:class ^(mpv)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(Winetricks)$, float on
windowrule = match:class ^(zenity)$, float on
windowrule = match:class ^(putty)$, float on
windowrule = match:class ^(gcolor3)$, float on
windowrule = match:class ^(nl.hjdskes.gcolor3)$, float on
windowrule = match:class ^(xarchiver)$, float on
windowrule = match:class ^(Xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(org.gnome.Solanum)$, float on

## Fix Thunar Delete

windowrule = match:class ^(thunar)$, match:title ^(Progreso de las operaciones de archivo)$, float on
windowrule = match:class ^(thunar)$, match:title ^(Renombrar)(.*)$, float on

# ---

windowrule = match:class ^(steam)$, border_size 0
windowrule = match:class ^(obsidian)$, border_size 0
windowrule = match:class ^(firefox-esr)$, border_size 0
windowrule = match:class ^(Chromium)$, border_size 0
windowrule = match:class ^(firefox)$, border_size 0
windowrule = match:class ^(Mozilla Firefox)$, border_size 0
windowrule = match:class ^(zathura)$, border_size 0
windowrule = match:class ^(VirtualBox Manager)$, border_size 0
windowrule = match:class ^(VirtualBox Machine)$, border_size 0
windowrule = match:class ^(org\.pwmt\.zathura)$, border_size 0
windowrule = match:class ^(Ferdium)$, border_size 0
windowrule = match:class ^(thunar)$, border_size 0

# ---

# Opacity and blur

# Simulate Active opacity and inactive opacity and configure the rest
windowrule = match:class ^.*$, opacity 0.92 0.85

windowrule = match:class ^(gcolor3)$, opacity 1 1
windowrule = match:class ^(steam)$, opacity 1 1
windowrule = match:class ^(Gimp-2\.10)$, opacity 1 1
windowrule = match:class ^(ferdium)$, opacity 0.98 0.95
windowrule = match:class ^(firefox-esr)$, opacity 0.94 0.88
windowrule = match:class ^(mpv)$, opacity 0.95 0.80
windowrule = match:class ^(obsidian)$, opacity 0.98 0.94
windowrule = match:class ^(kitty)$, opacity 0.86 0.75
windowrule = match:class ^(thunar)$, opacity 0.85 0.75
windowrule = match:class ^(Xdg-desktop-portal-gtk)$, opacity 0.85 0.75
windowrule = match:class ^(electron)$, opacity 0.85 0.70
windowrule = match:class ^(firefox-esr)$, match:title ^(Carga de archivos)$, opacity 0.85 0.70

# ---

# Xwaylandvideobridge
windowrule = match:class ^(xwaylandvideobridge)$, opacity 0.0 override 0.0 override
windowrule = match:class ^(xwaylandvideobridge)$, no_anim on
windowrule = match:class ^(xwaylandvideobridge)$, no_initial_focus on
windowrule = match:class ^(xwaylandvideobridge)$, max_size 1 1
windowrule = match:class ^(xwaylandvideobridge)$, no_blur on

# Swaync notification panel

#layerrule = blur on, match:namespace ^(.*swaync.*)$
#layerrule = ignore_alpha 0.5, match:namespace ^(.*swaync.*)$
